import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { db } from "../firebase";
import {
  collection,
  onSnapshot,
  doc,
  updateDoc,
  addDoc,
  deleteDoc,
  getDocs
} from "firebase/firestore";

export default function Admin() {
  const navigate = useNavigate();

  // ---------------- STATE ----------------
  const [tab, setTab] = useState("matches");

  const [matches, setMatches] = useState([]);
  const [players, setPlayers] = useState([]);

  // EDIT
  const [editHome, setEditHome] = useState("");
  const [editAway, setEditAway] = useState("");
  const [foundMatchId, setFoundMatchId] = useState(null);

  const [scoreHome, setScoreHome] = useState("");
  const [scoreAway, setScoreAway] = useState("");
  const [status, setStatus] = useState("Upcoming");

  // CREATE
  const [homeTeam, setHomeTeam] = useState("");
  const [awayTeam, setAwayTeam] = useState("");

  // PLAYER
  const [newPlayer, setNewPlayer] = useState("");

  // ---------------- AUTH ----------------
  useEffect(() => {
    const isAuth = localStorage.getItem("adminAuth");
    if (!isAuth) navigate("/admin-login");
  }, []);

  // ---------------- FIREBASE ----------------
  useEffect(() => {
    const unsub = onSnapshot(collection(db, "matches"), (snap) => {
      setMatches(snap.docs.map((d) => ({ id: d.id, ...d.data() })));
    });
    return () => unsub();
  }, []);

  useEffect(() => {
    const unsub = onSnapshot(collection(db, "players"), (snap) => {
      setPlayers(snap.docs.map((d) => ({ id: d.id, ...d.data() })));
    });
    return () => unsub();
  }, []);

  // ---------------- FIND MATCH ----------------
  const findMatch = (home, away) => {
    const m = matches.find(
      (x) => x.homeTeam === home && x.awayTeam === away
    );

    if (m) {
      setFoundMatchId(m.id);
      setScoreHome(m.scoreHome ?? "");
      setScoreAway(m.scoreAway ?? "");
      setStatus(m.status ?? "Upcoming");
    } else {
      setFoundMatchId(null);
    }
  };

  // ---------------- ADD PLAYER ----------------
  const addPlayer = async () => {
    if (!newPlayer) return;

    await addDoc(collection(db, "players"), {
      name: newPlayer.trim()
    });

    setNewPlayer("");
  };

  // ---------------- CREATE MATCH ----------------
  const addMatch = async () => {
    if (!homeTeam || !awayTeam) return;

    await addDoc(collection(db, "matches"), {
      homeTeam,
      awayTeam,
      scoreHome: null,
      scoreAway: null,
      status: "Upcoming",
      autoGenerated: false
    });

    setHomeTeam("");
    setAwayTeam("");
  };

  // ---------------- UPDATE MATCH ----------------
  const updateMatch = async () => {
    if (!foundMatchId) return alert("Match not found!");

    const h = Number(scoreHome);
    const a = Number(scoreAway);

    const valid =
      scoreHome !== "" &&
      scoreAway !== "" &&
      !isNaN(h) &&
      !isNaN(a);

    await updateDoc(doc(db, "matches", foundMatchId), {
      scoreHome: valid ? h : null,
      scoreAway: valid ? a : null,
      status: valid ? "Finished" : status
    });

    alert("Updated!");
  };

  // ---------------- OPTIMIZED LEAGUE ----------------
  const generateLeague = async () => {
    let names = players.map((p) => p.name);

    if (names.length < 2) {
      alert("Need at least 2 players");
      return;
    }

    let isOdd = names.length % 2 !== 0;
    if (isOdd) names.push("BYE");

    const n = names.length;
    const rounds = n - 1;
    const half = n / 2;

    let arr = [...names];
    let allDays = [];

    for (let r = 0; r < rounds; r++) {
      let matches = [];

      for (let i = 0; i < half; i++) {
        let home = arr[i];
        let away = arr[n - 1 - i];

        if (home !== "BYE" && away !== "BYE") {
          matches.push({ homeTeam: home, awayTeam: away });
        }
      }

      allDays.push({ day: r + 1, matches });

      const fixed = arr[0];
      const rest = arr.slice(1);
      rest.unshift(rest.pop());
      arr = [fixed, ...rest];
    }

    // Reverse fixtures
    let totalDays = [...allDays];

    allDays.forEach((md, i) => {
      totalDays.push({
        day: allDays.length + i + 1,
        matches: md.matches.map((m) => ({
          homeTeam: m.awayTeam,
          awayTeam: m.homeTeam
        }))
      });
    });

    for (let md of totalDays) {
      for (let m of md.matches) {
        await addDoc(collection(db, "matches"), {
          homeTeam: m.homeTeam,
          awayTeam: m.awayTeam,
          scoreHome: null,
          scoreAway: null,
          status: "Upcoming",
          matchDay: md.day,
          autoGenerated: true
        });
      }
    }

    alert("🔥 League Generated!");
  };
  // ---------------- Clear Curreny LEAGUE ----------------
  const clearLeague = async () => {
  const confirm = window.confirm(
    "⚠️ This will delete ALL matches. Are you sure?"
  );

  if (!confirm) return;

  const snap = await getDocs(collection(db, "matches"));

  const promises = snap.docs.map((docItem) =>
    deleteDoc(doc(db, "matches", docItem.id))
  );

  await Promise.all(promises);

  alert("✅ League cleared!");
  };

  const logout = () => {
    localStorage.removeItem("adminAuth");
    navigate("/");
  };

  return (
    <div style={styles.page}>
      {/* HEADER */}
      <div style={styles.header}>
        <h1>🔐 Admin Panel</h1>

        <div style={styles.topBtns}>
          <button style={styles.homeBtn} onClick={() => navigate("/")}>
            🏠
          </button>
          <button style={styles.logoutBtn} onClick={logout}>
            Logout
          </button>
        </div>
      </div>

      {/* TABS */}
      <div style={styles.tabs}>
        <button onClick={() => setTab("matches")} style={tab === "matches" ? styles.activeTab : styles.tab}>Matches</button>
        <button onClick={() => setTab("players")} style={tab === "players" ? styles.activeTab : styles.tab}>Players</button>
        <button onClick={() => setTab("edit")} style={tab === "edit" ? styles.activeTab : styles.tab}>Edit</button>
      </div>

      <div style={styles.container}>

        {/* MATCHES */}
        {tab === "matches" && (
          <div style={styles.card}>
            <h2>Matches</h2>

            {matches.map((m) => (
              <button
                key={m.id}
                style={styles.matchBtn}
                onClick={() => {
                  setEditHome(m.homeTeam);
                  setEditAway(m.awayTeam);
                  setFoundMatchId(m.id);
                  setScoreHome(m.scoreHome ?? "");
                  setScoreAway(m.scoreAway ?? "");
                  setStatus(m.status ?? "Upcoming");
                  setTab("edit");
                }}
              >
                {m.homeTeam} vs {m.awayTeam}
              </button>
            ))}
          </div>
        )}

        {/* PLAYERS */}
        {tab === "players" && (
          <>
            <div style={styles.card}>
              <h2>Add Player</h2>
              <input style={styles.input} value={newPlayer} onChange={(e) => setNewPlayer(e.target.value)} />
              <button style={styles.button} onClick={addPlayer}>Add</button>
            </div>

            <div style={styles.card}>
              <h2>Create Match</h2>
              <select style={styles.input} value={homeTeam} onChange={(e) => setHomeTeam(e.target.value)}>
                <option value="">Home</option>
                {players.map((p) => <option key={p.id}>{p.name}</option>)}
              </select>

              <select style={styles.input} value={awayTeam} onChange={(e) => setAwayTeam(e.target.value)}>
                <option value="">Away</option>
                {players.map((p) => <option key={p.id}>{p.name}</option>)}
              </select>

              <button style={styles.button} onClick={addMatch}>Create</button>
            </div>

            <button style={styles.button} onClick={generateLeague}>
              🔥 Generate League
            </button>
            <button
              style={styles.dangerBtn}
              onClick={clearLeague}
            >
              🗑️ Clear Current League
            </button>

            <button
              style={{ ...styles.button, background: "#28a745" }}
              onClick={() => navigate("/players")}
            >
              👥 View All Players
            </button>
          </>
        )}

        {/* EDIT */}
        {tab === "edit" && (
          <div style={styles.card}>
            <h2>Edit Match</h2>

            <select style={styles.input} value={editHome} onChange={(e) => { setEditHome(e.target.value); findMatch(e.target.value, editAway); }}>
              <option value="">Home</option>
              {players.map((p) => <option key={p.id}>{p.name}</option>)}
            </select>

            <select style={styles.input} value={editAway} onChange={(e) => { setEditAway(e.target.value); findMatch(editHome, e.target.value); }}>
              <option value="">Away</option>
              {players.map((p) => <option key={p.id}>{p.name}</option>)}
            </select>

            <input style={styles.input} placeholder="Home Score" value={scoreHome} onChange={(e) => setScoreHome(e.target.value)} />
            <input style={styles.input} placeholder="Away Score" value={scoreAway} onChange={(e) => setScoreAway(e.target.value)} />

            <button style={styles.button} onClick={updateMatch}>
              Update
            </button>
          </div>
        )}

      </div>
    </div>
  );
}

/* STYLES */
const styles = {
  page: { background: "#0d0d0d", minHeight: "100vh", color: "white", padding: 20 },
  header: { display: "flex", justifyContent: "space-between" },
  topBtns: { display: "flex", gap: 10 },
  tabs: { display: "flex", gap: 10, marginTop: 10 },
  tab: { padding: 10, background: "#111", color: "white", borderRadius: 8 },
  activeTab: { padding: 10, background: "#007bff", borderRadius: 8 },
  container: { maxWidth: 900, margin: "20px auto", display: "flex", flexDirection: "column", gap: 20 },
  card: { background: "#1a1a1a", padding: 20, borderRadius: 12 },
  input: { width: "100%", padding: 10, margin: "8px 0", background: "#111", color: "white" },
  button: { padding: 10, background: "#007bff", border: "none", color: "white", borderRadius: 8 },
  matchBtn: { width: "100%", padding: 10, background: "#111", marginBottom: 8, color: "white" },
  logoutBtn: { background: "red", padding: 8 },
  homeBtn: { background: "#007bff", padding: 8 },
  dangerBtn: {
    padding: 10,
    background: "#dc2626",
    border: "none",
    color: "white",
    borderRadius: 8,
    marginTop: "10px",
    cursor: "pointer"
          } 
};